[project]
name = "memorize-app"
version = "0.1.0"
description = "A simple app to help you memorize things."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.5",
    "types-requests>=2.32.4.20250913",
    "pillow>=10.0.0",
]
